function [Num,Theta,Phi,Name] = importelec(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [NUM,THETA,PHI,NAME] = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   [NUM,THETA,PHI,NAME] = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [Num,Theta,Phi,Name] = importfile('elec.dat',1, 5226);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/12/15 15:10:42

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 1;
    endRow = 5226;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Num = dataArray{:, 1};
Theta = dataArray{:, 2};
Phi = dataArray{:, 3};
Name = dataArray{:, 4};


